### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by marc-etienne** [fireeye/FIDL#1]
Hi!

Great job on providing a higher level API for Hex-Rays decompiler!

There are a few bugs we've encountered when we first tried it and would like to contribute patches to fix them. However, the license isn't explicitly given. I know, it's GitHub, and you probably want people to fork, but legally we have no right to republish (fork) without your explicit consent. You probably also want to protect yourself and/or FireEye and keep a copyright notice and credit in forks.

It mentions MIT here: https://github.com/fireeye/FIDL/blob/master/setup.py#L22. Should it be MIT?

Once this is fixed we'll open pull requests with the fixes,

Thanks!
M-E

**Comment by carlosgprado** [comment]
Hi Marc,

good catch, it is added now (MIT).
We are looking forward to your contributions! :)

Cheers,
Carlos
