### ISSUE TITLE
Do you have plan to support IDA 7.0?

### ISSUE THREAD

**Issue by xrkk** [fireeye/FIDL#11]
Do you have plan to support IDA 7.0?

**Comment by carlosgprado** [comment]
Hi, we don't plan to go down the rabbit hole of trying to support old versions of IDA. That said, have you tried this release? https://github.com/fireeye/FIDL/releases/tag/v1.01

This supports Python 2.7 but you may still have to tweak it a bit (the API changes so frequently...)

Hope this helps!
