### ISSUE TITLE
`my_decompile` fails on IDA 7.0

### ISSUE THREAD

**Issue by NSExceptional** [fireeye/FIDL#16]
I realize this repo doesn't strive to support Python 2 / IDA < 7.4, but I think a lot of it works out of the box except for this code right here: https://github.com/fireeye/FIDL/blob/e6ceb000cda43b450717eb171309c02dee06dd4f/FIDL/decompiler_utils.py#L1070-L1073

The version of this function present in 7.0 only accepts an address and a failure pointer, no flags. Would it be possible to somehow detect which one is available and call that? Or to add a new Python 2.7 and IDA < 7.4 release to call `decompile()` without the flags?

**Comment by carlosgprado** [comment]
Hi,

the IDAPython API for the decompiler changes quite frequently, many times breaking backwards compatibility. This means that it would be a large effort for us to keep up / support all versions. We have decided to try to support the latest version only.

That said, if you are really interested, tell me a way to DM you and I'll try to give you some pointers :)

**Comment by NSExceptional** [comment]
Hi Carlos,

Sure! You can DM me on Twitter or email me tannerbennett@me.com

**Comment by NSExceptional** [comment]
@carlosgprado I have not heard from you yet so I would like to reiterate that the `my_decompile` function is the _only_ broken component on 7.0 in many areas of this library, but the fact that all of the entrypoints expect your custom `cfunc_t` wrapper to be passed in—only to use the `cfunc_t` it carries—prevents me from working around this.

If your functions accepted `cfunc_t` instead, I could work around it in many cases without modifying the source. I realize that is not a very organized way to present an API, so it would be ideal if `my_decompile` could simply support the two different versions of `ida_hexrays.decompile()` :)

If that is not acceptable either, then I would like to publish a version for <7.4 on pip that I could maintain for others in my position. What do you think about this?
