### ISSUE TITLE
Simplify the API and add a helper function to get all xrefs-to a function

### ISSUE THREAD

**Issue by ITAYC0HEN** [fireeye/FIDL#6]
As far as I understand, currently, if one wants to get all the calls to a certain function, they have two options:

1. `display_all_calls_to (function)`
https://github.com/fireeye/FIDL/blob/6b127946b704d4e5f027c48cdb02cbdbef4d8890/FIDL/decompiler_utils.py#L1302-L1307

2. `find_all_calls_to (f_name, ea)`
https://github.com/fireeye/FIDL/blob/6b127946b704d4e5f027c48cdb02cbdbef4d8890/FIDL/decompiler_utils.py#L2250-L2255

While the `display_all_calls_to` prints all the calls to a function globally (across the entire binary), the latter, `find_all_calls_to`, returns only the xrefs to a function from a specific function (which `ea` belongs to`).

The problem is that the name `find_all_calls_to` is confusing due to the localization of the search-range (to a specific function), and that there is no option to get a list of `callObj` for all the calls to a function, globally.

I suggest having three functions:

1. `display_all_calls_to (function)` - keep as is
2. `find_all_calls_to_from_function (f_name, ea)` will behave as the current `find_all_calls_to` 
3. `find_all_calls_to (function)` - will return a list of `callObj` for all the xrefs, globally

**Comment by carlosgprado** [comment]
Good point. I'll take a stab at it soon(TM)

**Comment by carlosgprado** [comment]
I ended up renaming [`find_all_calls_to`](https://fidl.readthedocs.io/en/latest/api.html#decompiler_utils.find_all_calls_to) -> [`find_all_calls_to_within`](https://fidl.readthedocs.io/en/latest/api.html#decompiler_utils.find_all_calls_to_within), but apart from naming it essentially implements your suggestion.

Many thanks :)
