### ISSUE TITLE
pseudoViewer Question

### ISSUE THREAD

**Issue by dparnishchev** [fireeye/FIDL#9]
Hello!
First of all, I'd like to thank you for making FIDL public, it really helps!

I have a question regarding the following code from FIDL decompiler_utils.py:

```
if not has_cached_cfunc(ea):
    # Open the disassembly view here
    # to populate the cache
    pw = pseudoViewer()
    pw.show(ea=ea)
try:
    cf = decompile(ea=ea, flags=ida_hexrays.DECOMP_NO_WAIT)
except ida_hexrays.DecompilationFailure as e:
    print("Failed to decompile @ {:X}".format(ea))
    cf = None
```

This code creates a lot of decompiler windows and slows down or even hangs IDA while working with large databases. If I don't use pseudoViewer and just call decompile() for target functions, code works fine (at least as I see).
Can you explain why you decided to use pseudoViewer? What are its benefits comparing to omitting this code and just using decompile()?

**Comment by carlosgprado** [comment]
Hi,

this was one of the major hurdles we had when developing FIDL. For some reason, probably related to object lifecycles, the analysis fails if you try to run it through all functions in a loop. We determined that the function had to be "visited" prior to the analysis, something that the pseudoViewer achieves.

We are aware that this workaround is... sub-optimal to say the least (we call it "Hacking like in the movies(TM)) and are working to improve this. IDA 7.5 should include a little API change that allows us to remove the "WAIT_BOX" (the one flashing continuosly during the analysis)

I spent a lot of time looking at this and couldn't find a better way to do it, so if you happen to know one, I'll buy you a beer. Actually, a whole keg :D

**Comment by carlosgprado** [comment]
FYI, the need for this has been removed in e4939489bf353013b9e7ca1b44bc2ec5a5884871 as well as the (very) annoying `Decompiling...` dialog. This means that you can run a CPU intensive script in a loop now and IDA won't be catching the window focus anymore :)

**Comment by dparnishchev** [comment]
Great, thanks!
